products.products_form:
  path: '/products/form'
  defaults:
    _form: '\Drupal\products\Form\ProductsForm'
    _title: 'productsForm'
  requirements:
    _access: 'TRUE'

products.quickdelete:
  path: '/products/delete/{id}/quickedit'
  defaults:
    _controller: '\Drupal\products\Controller\ProductsController::openQuickEditModalForm'
    _title: 'Quick Edit Employee'
  requirements:
    _permission: 'access content'